### PR TITLE
created and added version text file in the name directory

### PR DESCRIPTION
**Pull request by unna97**
Added the files as mentioned in #2

### CODE REVIEW

**Comment by unna97** [comment]
finished task #3

**Comment by MridulS** [comment]
Thanks @unna97!

Can you update the version of networkx on your machine? NetworkX 2.7.1 is the latest one.

Do also check your python version.

**Comment by unna97** [comment]
Yes, @MridulS, I updated the package and created a different environment. I have been networkx user and absolutely love the package.

**Comment by MridulS** [comment]
thanks @unna97, can you push the changes to this PR?
The nx_version.txt file still shows 2.5 as the version.

**Comment by unna97** [comment]
@MridulS  just updated the version

**Pull request merged**
