### PR TITLE
create nx_version.txt and update nx_dev_test_output.txt

### PR DESCRIPTION
**Pull request by PurviChaurasia**
First Task completed!

### CODE REVIEW

**Comment by PurviChaurasia** [comment]
In reference to issue #149 and #152

**Comment by PurviChaurasia** [comment]
@MridulS Kindly merge the PR if no changes are required.

**Comment by PurviChaurasia** [comment]
Done with #5

**Comment by MridulS** [comment]
thanks for this @PurviChaurasia! Could you please use different branches for different tasks (it's fine for this PR!), this makes the review process easier. Ideally you should never be working off from your `main` branch!

**Pull request merged**
