### PR TITLE
Completed the task "Setup local development environment for NetworkX #3".

### PR DESCRIPTION
**Pull request by Saumay1**
Please review it.

### CODE REVIEW

**Comment by MridulS** [comment]
2022-round-1/Saumay1/nx_pull_requests.txt is an empty file right now. Could you please remove it from this PR? Thanks!

**Comment by Saumay1** [comment]
Sure! Deleted nx_pull_requests.txt
I thought we had to make one and then as we progressed we had to add the links of pull requests to it.

**Comment by MridulS** [comment]
Thanks!

**Comment by Saumay1** [comment]
Thanks for reviewing it, @MridulS :)

**Pull request merged**
