### PR TITLE
Created explanatory jupyter notebook

### LINKED ISSUE #8: Create an explanatory Jupyter notebook
[Everyone can do this task. There is no need to claim/assign this issue]

Once you have [installed networkx](https://github.com/networkx/outreachy/issues/2) and are [comfortable with the NetworkX API](https://github.com/networkx/outreachy/issues/5) the next task is to create a Jupyter Notebook and submit that notebook to this repository. The Outreachy project is about creating Pedagogical Interactive Notebooks and this task will help you with getting familiar with the Jupyter notebook interface.

The applicant needs to submit a Jupyter notebook (`.ipynb` file) which does the following operations:

- Create a [random erdos-renyi graph](https://networkx.org/documentation/latest/reference/generated/networkx.generators.random_graphs.erdos_renyi_graph.html#erdos-renyi-graph) with 100 nodes and a edge probability of 0.3
- Plot the [degree_centrality](https://networkx.org/documentation/latest/reference/algorithms/generated/networkx.algorithms.bipartite.centrality.degree_centrality.html) distribution (a histogram of the degree centrality values).
- Change the edge probability of the erdos-reyni graph to 0.6 and plot the degree centrality distribution again.
- Infer the changes in the plots, why does the degree centrality distribution change. Create a markdown cell in the jupyter notebook and write what you can infer from the plots. 
- Create a random [barabasi_albert_graph](https://networkx.org/documentation/latest/reference/generated/networkx.generators.random_graphs.barabasi_albert_graph.html#barabasi-albert-graph) with 100 nodes and attach 3 edges to  a new node in the graph (`m=3`).
- Plot the [degree_centrality](https://networkx.org/documentation/latest/reference/algorithms/generated/networkx.algorithms.bipartite.centrality.degree_centrality.html) distribution (a histogram of the degree histogram).
- Infer the changes in the plots, why does the degree centrality distribution change between these 2 random graph generators Create a markdown cell in the jupyter notebook and write what you can infer from the plots. 

Create a pull request against this repository and add the file `2023-round-1/<your-github-username>/nx_notebook.ipynb` with the notebook which performs all the operations above.

### PR DESCRIPTION
**Pull request by singhmansi25**
Fixes #8
I have created the explanatory notebook.
@MridulS 
Please review it and provide me feedbacks, if any.
Thank you.

### CODE REVIEW

**Comment by singhmansi25** [comment]
@rossbar and @MridulS 
I wanted to work on some issues, can I make an issue on Mantel's theorem or a function to create peterson graph.
If these types of issues are fine, then can I work on it?
Otherwise, Please suggest me some better issues to work on.

**Comment by MridulS** [comment]
Feel free to create any issues on the networkx repo if you would like to add anything to networkx or if you think there is something that can be improved :)

**Comment by MridulS** [comment]
Thanks @singhmansi25 for your contribution!

**Comment by MasterC4t** [comment]
NX

**Pull request merged**
