### PR TITLE
jupyter notebook

### PR DESCRIPTION
**Pull request by Lukong123**
Here is my jupyter notebook which answers this issue https://github.com/networkx/outreachy/issues/8

### CODE REVIEW

**Comment by Lukong123** [comment]
Hello @MridulS, I hope to get from you on this issue https://github.com/networkx/outreachy/issues/8, I have created the jupyter notebook and I am open to any adjustments and corrections that might arise. Thanks

**Comment by Lukong123** [comment]
Hello sir, I am still waiting for your review so that I can correct where necessary.
Thanks.

**Comment by MridulS** [comment]
thanks for the ping @Lukong123, but reviewing the notebook would take a bit more time and there are a lot of notebooks already waiting for a review 😅
I'll get to it ASAP.

**Comment by Lukong123** [comment]
> thanks for the ping @Lukong123, but reviewing the notebook would take a bit more time and there are a lot of notebooks already waiting for a review sweat_smile I'll get to it ASAP.

Okay sir, thanks.

**Comment by MridulS** [comment]
Thanks @Lukong123! Looks good to me :)

**Pull request merged**
