### PR TITLE
Created nx_tutorial_script.py file

### PR DESCRIPTION
**Pull request by Sreeyusha**
Completed task #5 and created a python script file. @MridulS please guide me if  I have done any mistakes. Thank you

### CODE REVIEW

**Comment by Sreeyusha** [comment]
@MridulS I have created a python script file and commented on the output in the code itself. I have also attached the picture of the graph network that was coming as output when this code is compiled.[
plot figure
](url)

**Comment by Sreeyusha** [comment]
Hi, @MridulS I have linked task #4 commits to this branch. Is it ok to do that or I should create a separate branch and raise a separate PR? Please guide me if I have done any mistakes. Thankyou.

**Comment by MridulS** [comment]
> I have linked task https://github.com/networkx/outreachy/issues/4 commits to this branch. Is it ok to do that or I should create a separate branch and raise a separate PR? Please guide me if I have done any mistakes. Thankyou.

It's fine for now, but it's recommended to use clean branches while doing changes :)

**Comment by Sreeyusha** [comment]
> > I have linked task #4 commits to this branch. Is it ok to do that or I should create a separate branch and raise a separate PR? Please guide me if I have done any mistakes. Thankyou.
> 
> It's fine for now, but it's recommended to use clean branches while doing changes :)

Sure, I will keep this in my mind. Thank you @MridulS

**Comment by Sreeyusha** [comment]
Hi @MridulS. I changed my code a little bit so that the output will be understandable way. Please guide me if you need more requirements in this code. I will make sure that I try my best to fulfill all your requirements for code. Please correct me if I am wrong. Looking forward to your guidance. Thank you.

**Comment by MridulS** [comment]
Thanks!

**Pull request merged**
