### PR TITLE
Third contribution

### PR DESCRIPTION
**Pull request by deepthi1107**

### CODE REVIEW

**Comment by deepthi1107** [comment]
@MridulS, evaluate my PR and  guide me if I am wrong

**Comment by MridulS** [comment]
Thanks for your contribution! @deepthi1107 Could you also add some explanations about the degree distribution plots?

**Comment by deepthi1107** [comment]
@MridulS, I have made changes.

**Comment by MridulS** [comment]
It seems to be the same file without the explanations, can you have a look again? Thanks!

**Comment by deepthi1107** [comment]
I am making changes may be they are not reflecting

**Comment by deepthi1107** [comment]
I will look into it

**Comment by deepthi1107** [comment]
Thanks @MridulS

**Comment by deepthi1107** [comment]
@MridulS I have done changes

**Comment by MridulS** [comment]
Thanks for your contribution!

**Pull request merged**
