### PR TITLE
First task

### PR DESCRIPTION
**Pull request by arpitadash**
Installing and adding networkx version

### CODE REVIEW

**Comment by MridulS** [comment]
thanks @arpitadash!
Can you remove the the extra `nx_version.txt` file in this PR?

**Comment by arpitadash** [comment]
> thanks @arpitadash! Can you remove the the extra `nx_version.txt` file in this PR?

Sure! I removed the extra file.

**Comment by arpitadash** [comment]
Hey @MridulS. Can you look into this pull request and suggest changes? Is there another algorithm I can start working on?

**Comment by arpitadash** [comment]
@MridulS A reminder to look into this PR. Thanks!

**Comment by MridulS** [comment]
Looks good! Thanks @arpitadash!

**Pull request merged**
