### PR TITLE
Task 3 pull request, Task 4 nx_tutorial_script and Task 5 Jupyter Notebook

### PR DESCRIPTION
**Pull request by NikitaSharma1**
python script

### CODE REVIEW

**Review by MridulS — COMMENTED** [review]
This looks good! But can you change the name of the graph variable from something other than `NetworkX`. It works but naming variables as package names should be avoided.

Can you also print out the `shortest_path` that you have calculated? Thanks!

**Comment by NikitaSharma1** [comment]
Sure sir, I changed the name of the graph variable, printed the shortest path and also added Task 5, the jupyter notebook.

**Comment by NikitaSharma1** [comment]
Sure sir, I changed the name of the graph variable, printed the shortest path and also added Task 5, the jupyter notebook.

**Comment by NikitaSharma1** [comment]
@MridulS I added the link to my pull request (Task 3). Can you please check my pull request in networkx [(https://github.com/networkx/networkx/pull/5491)](Link)

**Comment by MridulS** [comment]
This looks great! Thanks @NikitaSharma1!

**Pull request merged**
