### PR TITLE
Python script 5

### PR DESCRIPTION
**Pull request by aliveevie**
I have create the python script for DiGraph

### CODE REVIEW

**Comment by MridulS** [comment]
Thanks @aliveevie! All looks good but there is a typo in the name of the file: `nx_pull_requestx.txt` should be `nx_pull_requests.txt`, could you please fix that. Thanks!

**Comment by aliveevie** [comment]
Hello, I have updated the file name,
https://github.com/networkx/outreachy/pull/56/commits/52a788e065a12260f516b6cb5f89211cc6febc70

**Comment by MridulS** [comment]
Thanks! and it looks like the same files are also in https://github.com/networkx/outreachy/pull/56/ so I will close this PR and review https://github.com/networkx/outreachy/pull/56/

**Comment by aliveevie** [comment]
ok sir, what will I do now, Will I make another PR

**Comment by MridulS** [comment]
No need to do that :) https://github.com/networkx/outreachy/pull/56 had all the changes from this PR too.

**Comment by aliveevie** [comment]
ok

> No need to do that :) #56 had all the changes from this PR too.

ok, is it also going to be merge into main

**Pull request closed without merging**
