### PR TITLE
Setup local development environment for NetworkX

### PR DESCRIPTION
**Pull request by Ytemiloluwa**
Setup local development environment for NetworkX #3

### CODE REVIEW

**Comment by MridulS** [comment]
@Ytemiloluwa could you remove the tutorial script (third task) from this PR? It's always better to use a new branch for a new pull request. Thanks!

**Comment by Ytemiloluwa** [comment]
> @Ytemiloluwa could you remove the tutorial script (third task) from this PR? It's always better to use a new branch for a new pull request. Thanks!

should I drop the last commit or amend it ?

**Comment by Ytemiloluwa** [comment]
> @Ytemiloluwa could you remove the tutorial script (third task) from this PR? It's always better to use a new branch for a new pull request. Thanks!

Done !!!

**Comment by MridulS** [comment]
Thanks!

**Pull request merged**
